language: cpp

compiler:
  - clang
  - gcc

install:
  - "git clone https://github.com/google/googletest.git"
  - "pushd ."
  - "cd googletest && mkdir build && cd build && cmake .. && make"
  - "popd"
  - "pwd"
  - "ls -al"
  - "cp -r ./googletest/googlemock/include/gmock /usr/local/include/gmock"
  - "cp -r ./googletest/googletest/include/gtest /usr/local/include/gtest"
  - "cp ./googletest/build/lib/*.a /usr/local/lib/"

script:
  - make googletest
